### ISSUE TITLE
Refactor galaxy-server secret logic

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/galaxy-operator#99]
**Describe the bug**

We have a task that generates the `{{ ansible_operator_meta.name }}-server` k8s secret in the galaxy-api role.

```
- name: galaxy-server secret
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.secret.yaml.j2') | from_yaml }}"
  with_items:
    - galaxy-server
  no_log: "{{ no_log }}"
```

The problem is that that galaxy-server secret gets mounted into the content and worker deployment pods, which are in roles that get called earlier in the reconciliation loop.  So we end up with event errors like this:

```
51m         Warning   FailedMount                       pod/galaxy-worker-57bcf49489-9p7xf                        MountVolume.SetUp failed for volume "galaxy-server" : secret "galaxy-server" not found
51m         Warning   FailedMount                       pod/galaxy-content-cf6758b65-77vmm                        MountVolume.SetUp failed for volume "galaxy-server" : secret "galaxy-server" not found
```

As a result, the first time those pods come up, they are not successful (whether by crashloop, or errors in the pod logs).  The worker pod consistently restart 3 times before entering the running state.  

The content pod fails with errors like these in the logs because the -server secret is not mounted initially, so the postgres host is not set.

```
django.db.utils.OperationalError: [Errno -2] Name or service not known
```

**To Reproduce**
Fresh install

**Expected behavior**
server secret settings are set correctly in the content and worker pods on the first go.  This can be verified by checking the contents of the `settings.py` file inside the pod and comparing it with the base64 decoded values from the k8s server secret. 

## Proposed Fixes

**Option 1:**

Move all of the tasks the set `pulp_combined_settings` or append settings to `pulp_combined_settings` to the common role if possible. 

This may not be possible because it will create the secret too early to have all of the correct values.  For example, postgres upgrades have to happen after the content storage pvc has been created (currently in the postgres-content role).  

**Option 2:**

Call the content and worker roles again after the api role.  Not ideal because it means redundant tasks and is slower. 

**Option 3:** (preferred option I think)

Re-work things so that the content PVC can be created in the common role, or a net-new role before the `postgres` role.  But don't create the content deployment at that time.  Instead, wait to create the content and worker deployments until after the API deployment. 

This will still involve a lot of moving around `pulp_combined_settings` style tasks, but that is inevitable. 

---------------------------------

Additionally, we should implement a similar checksum to ensure that when there are changes to the -server secret and configmaps, the deployment cycles the pods so that the changes are picked up.  A pattern for this can be found here:
* https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/deployments/task.yaml.j2#L29-L46

**Comment by Denney-tech** [comment]
Option 4: 
Call the API role first?  I actually thought this one needed to start first.

**Comment by rooftopcellist** [comment]
@Denney-tech unfortunately, we can't call the API role first because the content PVC needs to be present at restore time for scenarios with `storage_type: file`.  
* https://github.com/ansible/galaxy-operator/blob/main/playbooks/galaxy.yaml#L89-L101

So when a restore object is created:
* Get data from backup pvc
* Create new Galaxy object. At this point, the Galaxy object is now being reconciled in parallel. The Restore reconciliation loop has a task that waits for the content pod to come up. 
* Create web and content roles, this imports variables and creates the content pvc
* Once the content pod is running, the restore role takes over again and copies the contents of `/var/lib/pulp` into the new deployment's content pvc.

I think we can probably refactor so that the server secret gets created earlier, and/or updated appropriately.

**Comment by rooftopcellist** [comment]
FYI, I don't hit this every time.  It seems like I hit it about 2/3 of the time.  This is because it sometimes gets to the api role task that creates the galaxy-server secret before the content and worker pods fully come up.

**Comment by Denney-tech** [comment]
I definitely think a refactor could simplify the deployment quite a bit, but I'm not familiar enough with the Backup/Restore processes to make any specific suggestions. I do think modeling the galaxy-operator after the awx-operator from the playbook up to the roles would make sense to me, since it's pretty tried and true as an ansible-operator.  The only thing galaxy-operator really has to do extra/different is supporting PVC/S3 backend configurations for the content pods.

Something that stands out to me here is that there seems to be a lot of redundant vars definitions (`raw_spec:` and subsequent vars referencing it for example) when awx-operator seems to refer spec parameters directly.  When I was making #100, I couldn't find `extra_settings:` being defined in the awx-operator playbook/roles for the life of me, so I just assumed it knows the var implicitly from the CR through the operator/sdk itself.

**Comment by rooftopcellist** [comment]
This was resolved as part of https://github.com/ansible/galaxy-operator/pull/80 

https://github.com/ansible/galaxy-operator/pull/80/commits/bbbc8b0adde2ea5423694f2a9a7201c1fd543bff
https://github.com/ansible/galaxy-operator/pull/80/commits/fe46e196c52a7d322211432461ad133bc86d663e
